name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt update && sudo apt install libboost-all-dev libmsgpack-dev ninja-build
    - name: Configure
      env:
        CXX: ${{ matrix.compiler }}
      run: ./configure
    - name: Build
      run: cmake --build build
    - name: Binary pubsub test
      run: ./build/pubsub_bin_test
    - name: Serialized pubsub test
      run: ./build/pubsub_test
    - name: Dragons memory test
      run: ./build/dragons_test


  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew update && brew install boost msgpack ninja
    - name: Configure
      run: ./configure
    - name: Build
      run: cmake --build build
    - name: Binary pubsub test
      run: ./build/pubsub_bin_test
    - name: Serialized pubsub test
      run: ./build/pubsub_test
    - name: Dragons memory test
      run: ./build/dragons_test

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --filter=-build/c++11 --exclude="include/catch.hpp" --exclude="build/*" --recursive .