name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && sudo apt install libboost-all-dev libmsgpack-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build

  build-macos:

        runs-on: macOS-latest

        steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: brew update && brew install boost msgpack
        - name: configure
          run: mkdir build && cd build && cmake ..
        - name: build
          run: cmake --build build
