name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./scripts/install_deps.sh
    - name: Configure
      env:
        CXX: ${{ matrix.compiler }}
      run: ./configure Debug
    - name: Build
      run: cmake --build build
    - name: Tests
      run: ./scripts/run_tests.sh

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: ./scripts/lint.sh

  single-header-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./scripts/install_deps.sh
        pip3 install -r simul/requirements.txt
    - name: Generate single header
      run: python3 simul/simul.py
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DSINGLE_H=ON ..
    - name: Build
      run: cmake --build build
    
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        path: include/shadesmar.h
